Quake_Muscle:
    lr: 0.0001
    lr_lp: 0.01
    num_hidden: 512
    num_projector_hidden: 512
    num_projector: 512
    num_heads: 8
    weight_decay: 2e-4
    max_epoch: 1000
    mask_rate: 0.1
    temperature: 0.5
    num_layers: 2
    encoder: gat
    decoder: gat
    activation: prelu
    in_drop: 0.2
    attn_drop: 0.1
    loss_fn: mse
    loss_weight: 0.2
    augmentation: drop_node
    drop_node_rate: 0.3
    drop_edge_rate: 0.2
    optimizer: adam
    replace_rate: 0.0
    alpha_l: 1
    scheduler: True
    mu: 0.8
    nu: 0.3
    rec_weight: 0.1
    zinb_weight: 0.8
    con_weight: 0.2